const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle } = require('discord.js');
const { query, one, many } = require('../db');
const { audit } = require('./audit');
const { getSettings, upsertMember } = require('./members');
const { isProtected } = require('./absences');

const addDays=(d,n)=>new Date(new Date(d).getTime()+Number(n)*86400000);
const addHours=(d,n)=>new Date(new Date(d).getTime()+Number(n)*3600000);

async function getLastClanActivity(userId){const r=await one(`SELECT MAX(s.clan_credit_at) AS value FROM activity_signups s JOIN activities a ON a.id=s.activity_id WHERE s.guild_id=$1 AND s.discord_id=$2 AND a.counts_for_clan=TRUE AND s.status IN('registered','bench') AND s.clan_credit_at IS NOT NULL`,[process.env.GUILD_ID,userId]);return r?.value||null;}
function staffProtected(member,s){return Boolean((s.role_admin_id&&member.roles.cache.has(s.role_admin_id))||(s.role_modo_id&&member.roles.cache.has(s.role_modo_id)));}
async function openPending(userId,type){return one(`SELECT * FROM pending_actions WHERE guild_id=$1 AND discord_id=$2 AND action_type=$3 AND status IN('pending','wait','extended') ORDER BY id DESC LIMIT 1`,[process.env.GUILD_ID,userId,type]);}

async function cancelPending(userId,type,reason){const p=await openPending(userId,type);if(!p)return;await query(`UPDATE pending_actions SET status='cancelled',staff_decision=$2,updated_at=NOW() WHERE id=$1`,[p.id,reason]);await audit({targetUserId:userId,source:'GOLEM',entityType:'pending_action',entityId:p.id,action:'PENDING_ACTION_CANCELLED',details:{reason}});}

function actionLabel(type){return type==='remove_clan'?'Retrait du rôle Clan':'Exclusion du serveur';}
function pendingMessage(p){const ts=Math.floor(new Date(p.execute_at).getTime()/1000);const e=new EmbedBuilder().setTitle('◈ GOLEM // ACTION EN ATTENTE').setDescription(`**${actionLabel(p.action_type)}**`).addFields({name:'Membre',value:`<@${p.discord_id}>`},{name:'Cause',value:p.reason},{name:'Échéance',value:`<t:${ts}:F> • <t:${ts}:R>`},{name:'Décision staff',value:p.staff_decision||'Aucune — délai normal'}).setColor('#e0b35e').setFooter({text:'GOLEM revérifie les rôles, activités, absences, vocal et sécurité avant toute action.'});const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`golem_mod:apply:${p.id}`).setLabel('APPLIQUER MAINTENANT').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`golem_mod:extend:${p.id}`).setLabel('PROLONGER').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`golem_mod:wait:${p.id}`).setLabel('ATTENDRE LE DÉLAI').setStyle(ButtonStyle.Secondary));return{embeds:[e],components:[row]};}

async function refreshPendingMessage(client,id){const p=await one(`SELECT * FROM pending_actions WHERE id=$1`,[id]);if(!p?.warning_message_id)return;const ch=client.guilds.cache.get(process.env.GUILD_ID)?.channels.cache.get(p.warning_channel_id);if(!ch?.isTextBased())return;const msg=await ch.messages.fetch(p.warning_message_id).catch(()=>null);if(msg)await msg.edit(pendingMessage(p));}

async function createPending(client,member,s,type,reason,due){if(Number(s.notice_hours)<=0)return null;if(!s.channel_actions_id){await audit({targetUserId:member.id,source:'GOLEM',entityType:'pending_action',action:'PENDING_ACTION_BLOCKED',details:{reason:'warning_channel_not_configured',actionType:type}});return null}const channel=member.guild.channels.cache.get(s.channel_actions_id);if(!channel?.isTextBased())return null;let executeAt=due;if(new Date(due)<=new Date())executeAt=addHours(new Date(),Number(s.notice_hours));let p;try{p=await one(`INSERT INTO pending_actions(guild_id,discord_id,action_type,reason,execute_at,warning_channel_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[process.env.GUILD_ID,member.id,type,reason,executeAt,channel.id])}catch(e){if(String(e.code)==='23505')return openPending(member.id,type);throw e}try{const msg=await channel.send(pendingMessage(p));await query(`UPDATE pending_actions SET warning_message_id=$2,updated_at=NOW() WHERE id=$1`,[p.id,msg.id]);await audit({targetUserId:member.id,source:'GOLEM',entityType:'pending_action',entityId:p.id,action:'PENDING_ACTION_CREATED',newValue:{actionType:type,reason,executeAt,channelId:channel.id,messageId:msg.id}});return{...p,warning_message_id:msg.id}}catch(e){await query(`UPDATE pending_actions SET status='cancelled',staff_decision='warning_failed',updated_at=NOW() WHERE id=$1`,[p.id]);await audit({targetUserId:member.id,source:'GOLEM',entityType:'pending_action',entityId:p.id,action:'PENDING_ACTION_BLOCKED',details:{reason:'warning_message_failed',error:e.message}});return null}}

async function safetyBlocks(s){return Boolean(s?.safety_hold_until&&new Date(s.safety_hold_until)>new Date());}

async function executePendingAction(client,id,actorId=null,source='GOLEM'){const p=await one(`SELECT * FROM pending_actions WHERE id=$1 AND guild_id=$2`,[id,process.env.GUILD_ID]);if(!p||!['pending','wait','extended'].includes(p.status))return{executed:false,reason:'action_fermée'};const s=await getSettings();if(!s?.enabled)return{executed:false,reason:'GOLEM_désactivé'};if(s.paused)return{executed:false,reason:'GOLEM_en_pause'};if(await safetyBlocks(s))return{executed:false,reason:'sécurité_après_redémarrage'};const guild=client.guilds.cache.get(process.env.GUILD_ID);const member=await guild?.members.fetch(p.discord_id).catch(()=>null);if(!member){await query(`UPDATE pending_actions SET status='cancelled',staff_decision='membre absent',updated_at=NOW() WHERE id=$1`,[p.id]);return{executed:false,reason:'membre_introuvable'}};if(staffProtected(member,s)){await cancelPending(member.id,p.action_type,'staff_protégé');return{executed:false,reason:'staff_protégé'}};if(await isProtected(member.id,s)){await cancelPending(member.id,p.action_type,'absence_protégée');return{executed:false,reason:'absence_protégée'}};
 if(p.action_type==='remove_clan'){
  if(Number(s.clan_inactivity_days)<=0){await cancelPending(member.id,p.action_type,'règle_Clan_désactivée');return{executed:false,reason:'règle_Clan_désactivée'}}
  if(!s.role_clan_id||!member.roles.cache.has(s.role_clan_id)){await cancelPending(member.id,p.action_type,'rôle_Clan_absent');return{executed:false,reason:'rôle_Clan_absent'}}
  const row=await one(`SELECT * FROM members WHERE guild_id=$1 AND discord_id=$2`,[process.env.GUILD_ID,member.id]);const last=await getLastClanActivity(member.id);const ref=last||row?.clan_since||s.tracking_started_at;const due=addDays(ref,s.clan_inactivity_days);if(Date.now()<due.getTime()){await cancelPending(member.id,p.action_type,'inscription_Planning_récente');return{executed:false,reason:'activité_Planning_récente'}}
  await member.roles.remove(s.role_clan_id,'GOLEM : inactivité Planning');if(s.role_guardian_id)await member.roles.add(s.role_guardian_id,'GOLEM : Clan → Gardien');await query(`UPDATE members SET clan_since=NULL,guardian_since=NOW(),updated_at=NOW() WHERE guild_id=$1 AND discord_id=$2`,[process.env.GUILD_ID,member.id]);await query(`UPDATE pending_actions SET status='executed',staff_user_id=COALESCE($2,staff_user_id),updated_at=NOW() WHERE id=$1`,[p.id,actorId]);await audit({actorId,targetUserId:member.id,source,entityType:'member_role',entityId:s.role_clan_id,action:'CLAN_ROLE_REMOVED',details:{pendingActionId:p.id,guardianRoleAdded:Boolean(s.role_guardian_id)}});return{executed:true};
 }
 if(p.action_type==='kick_guardian'){
  if(Number(s.guardian_voice_days)<=0){await cancelPending(member.id,p.action_type,'règle_Gardien_désactivée');return{executed:false,reason:'règle_Gardien_désactivée'}}
  const guardian=Boolean(s.role_guardian_id&&member.roles.cache.has(s.role_guardian_id));const clan=Boolean(s.role_clan_id&&member.roles.cache.has(s.role_clan_id));if(!guardian||clan){await cancelPending(member.id,p.action_type,'plus_Gardien_seul');return{executed:false,reason:'plus_Gardien_seul'}}
  const row=await one(`SELECT * FROM members WHERE guild_id=$1 AND discord_id=$2`,[process.env.GUILD_ID,member.id]);const ref=row?.last_valid_voice_at||row?.guardian_since||s.tracking_started_at;const due=addDays(ref,s.guardian_voice_days);if(Date.now()<due.getTime()){await cancelPending(member.id,p.action_type,'vocal_récent');return{executed:false,reason:'vocal_récent'}}
  await member.kick(`GOLEM : aucune session vocale valide de ${s.voice_min_minutes} min dans le délai configuré.`);await query(`UPDATE pending_actions SET status='executed',staff_user_id=COALESCE($2,staff_user_id),updated_at=NOW() WHERE id=$1`,[p.id,actorId]);await audit({actorId,targetUserId:member.id,source,entityType:'member',action:'MEMBER_KICKED',details:{pendingActionId:p.id}});return{executed:true};
 }
 return{executed:false,reason:'action_inconnue'};
}

async function scanModeration(client){const s=await getSettings();if(!s?.enabled||s.paused||await safetyBlocks(s))return;if(Number(s.notice_hours)<=0)return;const guild=client.guilds.cache.get(process.env.GUILD_ID);if(!guild)return;await guild.members.fetch();for(const member of guild.members.cache.values()){if(member.user.bot)continue;if(staffProtected(member,s))continue;await upsertMember(member,s);if(await isProtected(member.id,s)){await cancelPending(member.id,'remove_clan','absence_protégée');await cancelPending(member.id,'kick_guardian','absence_protégée');continue}const hasClan=Boolean(s.role_clan_id&&member.roles.cache.has(s.role_clan_id));const hasGuardian=Boolean(s.role_guardian_id&&member.roles.cache.has(s.role_guardian_id));
 if(hasClan){await cancelPending(member.id,'kick_guardian','rôle_Clan_prioritaire');if(Number(s.clan_inactivity_days)>0){const row=await one(`SELECT * FROM members WHERE guild_id=$1 AND discord_id=$2`,[process.env.GUILD_ID,member.id]);const last=await getLastClanActivity(member.id);const ref=last||row?.clan_since||s.tracking_started_at;const due=addDays(ref,s.clan_inactivity_days);const notice=addHours(due,-Number(s.notice_hours));if(Date.now()<notice.getTime())await cancelPending(member.id,'remove_clan','inscription_Planning_récente');else if(!await openPending(member.id,'remove_clan'))await createPending(client,member,s,'remove_clan',`Aucune inscription Planning valide depuis ${s.clan_inactivity_days} jour(s).`,due)}continue}
 await cancelPending(member.id,'remove_clan','rôle_Clan_absent');if(hasGuardian&&Number(s.guardian_voice_days)>0){const row=await one(`SELECT * FROM members WHERE guild_id=$1 AND discord_id=$2`,[process.env.GUILD_ID,member.id]);const ref=row?.last_valid_voice_at||row?.guardian_since||s.tracking_started_at;const due=addDays(ref,s.guardian_voice_days);const notice=addHours(due,-Number(s.notice_hours));if(Date.now()<notice.getTime())await cancelPending(member.id,'kick_guardian','vocal_récent');else if(!await openPending(member.id,'kick_guardian'))await createPending(client,member,s,'kick_guardian',`Aucune session vocale valide d’au moins ${s.voice_min_minutes} minute(s) dans les ${s.guardian_voice_days} dernier(s) jour(s).`,due)}else await cancelPending(member.id,'kick_guardian','pas_Gardien_seul');}}

async function executeDueActions(client){const s=await getSettings();if(!s?.enabled||s.paused||Number(s.notice_hours)<=0||await safetyBlocks(s))return;const rows=await many(`SELECT * FROM pending_actions WHERE guild_id=$1 AND status IN('pending','wait','extended') AND execute_at<=NOW() ORDER BY execute_at LIMIT 25`,[process.env.GUILD_ID]);for(const p of rows){try{await executePendingAction(client,p.id);await refreshPendingMessage(client,p.id)}catch(e){await audit({targetUserId:p.discord_id,source:'GOLEM',entityType:'pending_action',entityId:p.id,action:'PENDING_ACTION_EXECUTION_FAILED',details:{error:e.message}})}}}

async function listPending(){return many(`SELECT p.*,m.username,m.display_name FROM pending_actions p LEFT JOIN members m ON m.guild_id=p.guild_id AND m.discord_id=p.discord_id WHERE p.guild_id=$1 ORDER BY p.created_at DESC LIMIT 250`,[process.env.GUILD_ID]);}
function staffCan(interaction,s){return Boolean(interaction.memberPermissions?.has('Administrator')||interaction.memberPermissions?.has('ManageGuild')||(s.role_admin_id&&interaction.member?.roles.cache.has(s.role_admin_id))||(s.role_modo_id&&interaction.member?.roles.cache.has(s.role_modo_id)));}

async function handleModerationInteraction(client,interaction){if(interaction.isButton()&&interaction.customId.startsWith('golem_mod:')){const[,action,raw]=interaction.customId.split(':');const id=Number(raw),p=await one(`SELECT * FROM pending_actions WHERE id=$1 AND guild_id=$2`,[id,process.env.GUILD_ID]);if(!p){await interaction.reply({content:'Action introuvable.',ephemeral:true});return true}const s=await getSettings();if(!staffCan(interaction,s)){await interaction.reply({content:'❌ Réservé au staff GOLEM.',ephemeral:true});return true}if(action==='apply'){await interaction.deferReply({ephemeral:true});const r=await executePendingAction(client,id,interaction.user.id,'STAFF');await refreshPendingMessage(client,id).catch(()=>{});await interaction.editReply(r.executed?'✅ Action appliquée.':`ℹ️ Action non appliquée : ${r.reason}.`);return true}if(action==='wait'){await query(`UPDATE pending_actions SET status='wait',staff_decision='ATTENDRE LE DÉLAI',staff_user_id=$2,updated_at=NOW() WHERE id=$1`,[id,interaction.user.id]);await audit({actorId:interaction.user.id,targetUserId:p.discord_id,source:'STAFF',entityType:'pending_action',entityId:id,action:'PENDING_ACTION_WAIT',details:{executeAt:p.execute_at}});await refreshPendingMessage(client,id);await interaction.reply({content:'⏳ Délai conservé.',ephemeral:true});return true}if(action==='extend'){const modal=new ModalBuilder().setCustomId(`golem_mod_extend:${id}`).setTitle('Prolonger le délai');const input=new TextInputBuilder().setCustomId('hours').setLabel('Nombre d’heures à ajouter').setPlaceholder('24, 72, 168…').setRequired(true).setStyle(TextInputStyle.Short);modal.addComponents(new ActionRowBuilder().addComponents(input));await interaction.showModal(modal);return true}}
 if(interaction.isModalSubmit()&&interaction.customId.startsWith('golem_mod_extend:')){const id=Number(interaction.customId.split(':')[1]),p=await one(`SELECT * FROM pending_actions WHERE id=$1 AND guild_id=$2`,[id,process.env.GUILD_ID]);if(!p){await interaction.reply({content:'Action introuvable.',ephemeral:true});return true}const s=await getSettings();if(!staffCan(interaction,s)){await interaction.reply({content:'❌ Réservé au staff.',ephemeral:true});return true}const h=Number(interaction.fields.getTextInputValue('hours'));if(!Number.isInteger(h)||h<1||h>720){await interaction.reply({content:'❌ Entre 1 et 720 heures.',ephemeral:true});return true}const next=addHours(p.execute_at,h);await query(`UPDATE pending_actions SET status='extended',execute_at=$2,staff_decision=$3,staff_user_id=$4,extension_count=extension_count+1,updated_at=NOW() WHERE id=$1`,[id,next,`PROLONGÉ +${h}h`,interaction.user.id]);await audit({actorId:interaction.user.id,targetUserId:p.discord_id,source:'STAFF',entityType:'pending_action',entityId:id,action:'PENDING_ACTION_EXTENDED',oldValue:{executeAt:p.execute_at},newValue:{executeAt:next},details:{addedHours:h}});await refreshPendingMessage(client,id);await interaction.reply({content:`✅ Délai prolongé de ${h}h.`,ephemeral:true});return true}
 return false;
}

module.exports={scanModeration,executeDueActions,executePendingAction,listPending,handleModerationInteraction,refreshPendingMessage,getLastClanActivity,cancelPending};
