const { query, one, many } = require('../db');
const { audit } = require('./audit');
const { getSettings } = require('./members');

const weekdays={Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7};
function localParts(date,timeZone){const parts=new Intl.DateTimeFormat('en-CA',{timeZone,weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(date);const m=Object.fromEntries(parts.map(p=>[p.type,p.value]));return{weekday:weekdays[m.weekday],hour:Number(m.hour),key:`${m.year}-${m.month}-${m.day}`};}
function roleName(base,streak){return streak<=1?base:`${base} +${streak-1}`}
function isConsecutive(lastKey,currentKey){if(!lastKey)return false;const a=Date.parse(lastKey+'T00:00:00Z'),b=Date.parse(currentKey+'T00:00:00Z');return Number.isFinite(a)&&Number.isFinite(b)&&Math.round((b-a)/86400000)===7;}
async function rewardRole(guild,s,streak){let row=await one(`SELECT * FROM reward_roles WHERE guild_id=$1 AND streak_level=$2`,[process.env.GUILD_ID,streak]);let role=row&&guild.roles.cache.get(row.role_id);if(role)return role;role=await guild.roles.create({name:roleName(s.reward_base_name,streak),reason:'GOLEM : récompense hebdomadaire'});await query(`INSERT INTO reward_roles(guild_id,streak_level,role_id,role_name) VALUES($1,$2,$3,$4) ON CONFLICT(guild_id,streak_level) DO UPDATE SET role_id=EXCLUDED.role_id,role_name=EXCLUDED.role_name`,[process.env.GUILD_ID,streak,role.id,role.name]);return role;}
async function processWeeklyRewards(client){const s=await getSettings();if(!s?.enabled||s.paused||!s.reward_enabled)return;const now=new Date(),p=localParts(now,s.timezone||'Europe/Paris');if(p.weekday!==Number(s.reward_weekday)||p.hour!==Number(s.reward_hour))return;if(await one(`SELECT 1 FROM weekly_runs WHERE guild_id=$1 AND run_key=$2`,[process.env.GUILD_ID,p.key]))return;await query(`INSERT INTO weekly_runs(guild_id,run_key) VALUES($1,$2)`,[process.env.GUILD_ID,p.key]);const ranking=await many(`SELECT s.discord_id,COUNT(DISTINCT s.activity_id)::INTEGER n FROM activity_signups s JOIN activities a ON a.id=s.activity_id WHERE s.guild_id=$1 AND a.counts_for_clan=TRUE AND s.presence='present' AND a.scheduled_at<=NOW() AND a.scheduled_at>=NOW()-INTERVAL '7 days' GROUP BY s.discord_id ORDER BY n DESC`,[process.env.GUILD_ID]);if(!ranking.length||ranking[0].n<=0)return;const max=ranking[0].n,winners=ranking.filter(r=>r.n===max),guild=client.guilds.cache.get(process.env.GUILD_ID);await guild.members.fetch();const existing=await many(`SELECT * FROM reward_roles WHERE guild_id=$1`,[process.env.GUILD_ID]);for(const member of guild.members.cache.values()){const ids=existing.map(r=>r.role_id).filter(id=>member.roles.cache.has(id));if(ids.length)await member.roles.remove(ids,'GOLEM : rotation récompense').catch(()=>{})}for(const w of winners){const row=await one(`SELECT * FROM reward_streaks WHERE guild_id=$1 AND discord_id=$2`,[process.env.GUILD_ID,w.discord_id]);const streak=isConsecutive(row?.last_win_key,p.key)?Number(row.streak)+1:1;await query(`INSERT INTO reward_streaks(guild_id,discord_id,streak,last_win_key) VALUES($1,$2,$3,$4) ON CONFLICT(guild_id,discord_id) DO UPDATE SET streak=EXCLUDED.streak,last_win_key=EXCLUDED.last_win_key,updated_at=NOW()`,[process.env.GUILD_ID,w.discord_id,streak,p.key]);const role=await rewardRole(guild,s,streak),member=guild.members.cache.get(w.discord_id);if(member)await member.roles.add(role.id,'GOLEM : gagnant hebdomadaire').catch(()=>{});await audit({targetUserId:w.discord_id,source:'GOLEM',entityType:'weekly_reward',entityId:p.key,action:'WEEKLY_REWARD_GRANTED',newValue:{activityCount:max,streak,roleId:role.id,roleName:role.name}})}}
module.exports={processWeeklyRewards};
