const { ActionRowBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder } = require('discord.js');
const { ensureSettings,syncGuildMembers,upsertMember,getSettings,saveSettings,handleGuildMemberUpdate } = require('../services/members');
const { handleVoiceStateUpdate,recoverVoiceSessions } = require('../services/voice');
const { createPanelToken } = require('../services/access');
const { handleSignupButton } = require('../services/activities');
const { handleModerationInteraction } = require('../services/moderation');
const { audit } = require('../services/audit');
function baseUrl(){if(process.env.PUBLIC_URL)return process.env.PUBLIC_URL.replace(/\/+$/,'');if(process.env.KOYEB_PUBLIC_DOMAIN)return`https://${process.env.KOYEB_PUBLIC_DOMAIN}`;return`http://localhost:${process.env.PORT||3000}`;}
function staff(interaction,s){return Boolean(interaction.memberPermissions?.has('Administrator')||interaction.memberPermissions?.has('ManageGuild')||(s?.role_admin_id&&interaction.member?.roles.cache.has(s.role_admin_id))||(s?.role_modo_id&&interaction.member?.roles.cache.has(s.role_modo_id)));}
function registerDiscordEvents(client){client.on('guildCreate',async guild=>{if(guild.id!==process.env.GUILD_ID){console.warn(`GOLEM // serveur non autorisé : ${guild.name}`);await guild.leave().catch(()=>{});return}await ensureSettings(guild);await syncGuildMembers(guild);await recoverVoiceSessions(guild)});client.on('guildMemberAdd',m=>{if(m.guild.id===process.env.GUILD_ID)return upsertMember(m)});client.on('guildMemberUpdate',(a,b)=>handleGuildMemberUpdate(a,b,client.user?.id));client.on('voiceStateUpdate',handleVoiceStateUpdate);
 client.on('interactionCreate',async interaction=>{try{if(interaction.guildId&&interaction.guildId!==process.env.GUILD_ID){if(interaction.isRepliable())await interaction.reply({content:'GOLEM est réservé au serveur Les Golem.',ephemeral:true});return}if(interaction.isChatInputCommand()&&interaction.commandName==='golem'){const sub=interaction.options.getSubcommand(),s=await getSettings();if(sub==='status'){const e=new EmbedBuilder().setTitle('◈ GOLEM // LES GOLEM').addFields({name:'Bot',value:client.isReady()?'🟢 ONLINE':'🔴 OFFLINE',inline:true},{name:'Configuration',value:s?.enabled?'✅ ACTIVE':'⚙️ À CONFIGURER',inline:true},{name:'Automatisations',value:s?.paused?'⏸️ PAUSE':'▶️ ACTIVES',inline:true},{name:'Sécurité',value:s?.safety_hold_until&&new Date(s.safety_hold_until)>new Date()?`🛡️ jusqu’à <t:${Math.floor(new Date(s.safety_hold_until).getTime()/1000)}:R>`:'✅ normale'}).setColor('#b083ff');await interaction.reply({embeds:[e],ephemeral:true});return}if(!staff(interaction,s)){await interaction.reply({content:'❌ Réservé au staff GOLEM.',ephemeral:true});return}if(sub==='panel'){const token=await createPanelToken(interaction.user.id,120),url=`${baseUrl()}/panel?token=${encodeURIComponent(token)}`;const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setStyle(ButtonStyle.Link).setLabel('OUVRIR LE CONTROL PANEL').setURL(url));await interaction.reply({content:'◈ **GOLEM // CONTROL PANEL**\nLien privé valable 2 heures.',components:[row],ephemeral:true});return}if(sub==='pause'||sub==='resume'){const paused=sub==='pause';await saveSettings({paused});await audit({actorId:interaction.user.id,source:'STAFF',entityType:'guild_settings',entityId:process.env.GUILD_ID,action:paused?'GOLEM_PAUSED':'GOLEM_RESUMED'});await interaction.reply({content:paused?'⏸️ GOLEM est en pause. Le suivi continue, les automatismes sensibles sont bloqués.':'▶️ GOLEM a repris ses automatismes.',ephemeral:true});return}}
 if(interaction.isButton()){if(await handleSignupButton(interaction))return;if(await handleModerationInteraction(client,interaction))return}if(interaction.isModalSubmit()){if(await handleModerationInteraction(client,interaction))return}}
 catch(e){console.error('GOLEM // INTERACTION',e);if(interaction.isRepliable()){const payload={content:`❌ GOLEM : ${e.message||'erreur interne'}`,ephemeral:true};if(interaction.replied||interaction.deferred)await interaction.followUp(payload).catch(()=>{});else await interaction.reply(payload).catch(()=>{})}}});}
module.exports={registerDiscordEvents,baseUrl};
